os:
  - linux
language: c
dist: bionic

services:
  - docker

stages:
  - build_frr_docker_images

env:
  global:
    WITH_TRAVIS=1

jobs:
  include:
    - stage: build_frr_docker_images
      script:
        - export FRR_COMMIT_HASH=$(git rev-parse --short=7 HEAD) #Avoid temp travis commit.
        - . artifactory-ibm/frr_docker_version.sh && export FRR_IMAGE_TAG=frr:"$FRR_RELEASE"-"$FRR_UBI"-"$FRR_COMMIT_HASH"-"$FRR_SERIAL"
        - echo "Test existence of docker image:" $FRR_IMAGE_TAG
        - |
          artifactory-ibm/docker.sh pull "$FRR_IMAGE_TAG" "$FRR_COMMIT_HASH"
          if [ $? -eq 0 ]; then
            echo "Pull succeed " $FRR_IMAGE_TAG " Already exist image, so nothing to do"
          else
            if [[ "$(git cat-file -t $FRR_COMMIT_HASH)" != "commit" ]]; then
              echo "ERROR the commit hash " $FRR_COMMIT_HASH " do not exist, bye!" && /bin/false
            else
              docker/ubi-8/build.sh "$FRR_IMAGE_TAG" "$FRR_COMMIT_HASH" "$FRR_RELEASE" "$FRR_NAME" "$FRR_VENDOR"
              if [[ "$(docker images --format '{{.Tag}}'| grep "$FRR_COMMIT_HASH"  | wc -l)" == "0" ]]; then
                echo "ERROR building docker image" && /bin/false
              else
                artifactory-ibm/docker.sh push "$FRR_IMAGE_TAG" "$FRR_COMMIT_HASH"
                docker rmi "$FRR_IMAGE_TAG" # Clean all
              fi
            fi
          fi
