FRR_COMMIT_HASH=$(git rev-parse --short=7 HEAD)
FRR_UBI=ubi-8
FRR_SERIAL=13
FRR_RELEASE=frr-8.2.2
FRR_NAME=palmetto_frr
FRR_VENDOR=axon-net

export FRR_IMAGE_TAG=frr:"$FRR_RELEASE"-"$FRR_UBI"-"$FRR_COMMIT_HASH"-"$FRR_SERIAL"
export FRR_TOOLS_TAG=frr:"$FRR_RELEASE"-"$FRR_UBI"-"$FRR_COMMIT_HASH"-tools-"$FRR_SERIAL"

echo "FRR_IMAGE_TAG=$FRR_IMAGE_TAG"
echo "FRR_TOOLS_TAG=$FRR_TOOLS_TAG"
